### ISSUE TITLE
inconsistency in wetbulb

### ISSUE THREAD

**Issue by HoWol76** [coecms/frontdetection#13]
At the beginning of the function `wetbulb` there is a decision tree on whether the temperature field is in Kelvin or Degrees Celsius. But in the loop at the end of the function, there is no difference, even though a calculation is made that looks surprisingly similar to the saturation pressure, which seems to depend on this distinction.

**Comment by greensh16** [comment]
The Metpy functions have now replaced Malcolm's wetbulb function so this decision tree is no longer needed (or I guess there's an internal one in the metpy wetbulb function).
