### ISSUE TITLE
Unit handling

### ISSUE THREAD

**Issue by ccarouge** [coecms/frontdetection#2]
The code tries to handle temperature in C and K but the handling isn't great or complete.

This line in wetbulb will break if ta is in C:
`	delta_t=(ta-t_dewpoint)/steps`
At this point, ta is still in C but t_dewpoint is in K.

Possible solution: add a function to convert ta to K.

**Comment by aidanheerdegen** [comment]
Was wondering if it might be useful to use [Pint](https://pint.readthedocs.io/en/stable/index.html) and then noticed [pint-xarray](https://github.com/xarray-contrib/pint-xarray) is a thing, and [pint in cf-xarray](https://github.com/xarray-contrib/cf-xarray/pull/197) is a work in progress.

**Comment by greensh16** [comment]
Now using metpy which solves this problem.
