### ISSUE TITLE
Remove magic numbers

### ISSUE THREAD

**Issue by ccarouge** [coecms/frontdetection#5]
Magic numbers:
`		es=6.1094*np.exp((17.625*(ta-273.15))/(ta-30.11))`
`		es=6.1094*np.exp((17.625*(ta))/(ta+243.04))`
`	rh=((hus*(plev-es))/(0.622*(1-hus)*es))`
`	t_dewpoint=((243.5*np.log(e/6.112))/(17.67-np.log(e/6.112)))+273.15`
`		adiabatic_adj=850*(ta-cur_t)*(.00066)*(1+.00115*cur_t)`
180: conversion between rad and degrees
erad = 6371e3  : Need to say what it is.
re=6371e3: Same magic number as erad above but with a different variable name and re-defined in a different function

**Comment by aidanheerdegen** [comment]
Or replace with `metpy`. See #1

**Comment by greensh16** [comment]
Has now been replaced with metpy.
